### ISSUE TITLE
`prool/instances` is not exported in published npm package

### ISSUE THREAD

**Issue by L8D** [wevm/prool#16]
Hello. I installed version `0.0.12` and the `instances` are available under `prool/exports/instances` but not under `prool/instances`

```
Cannot find module 'prool/instances' or its corresponding type declarations.
  There are types at '.../node_modules/prool/_lib/exports/instances.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'. (tsserver 2307)
```

**Comment by jxom** [comment]
Can you provide a minimal reproduction?

**Comment by L8D** [comment]
@jxom 

```
mkdir foo && cd foo && npm init -y && npm install -D jest ts-jest typescript @types/jest prool && npx tsc --init && npx ts-jest config:init
cat - > myprooltest.test.ts <<EOF
import { createServer } from 'prool'
import { anvil } from 'prool/instances'

describe('my anvil server', () => {
	it('starts', async () => {
		const server = createServer({
			instance: anvil()
		})

		await server.start()
	})
})
EOF
npx jest
```

copy & paste into terminal and you will find the error below:

```
 FAIL  ./myprooltest.test.ts
  ● Test suite failed to run

    myprooltest.test.ts:2:23 - error TS2307: Cannot find module 'prool/instances' or its corresponding type declarations.

    2 import { anvil } from 'prool/instances'
                            ~~~~~~~~~~~~~~~~~

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.683 s
Ran all test suites.
```

**Comment by jxom** [comment]
Yeah Jest isn't really ESM friendly, especially with `package.json#exports`. Will probably need to add proxy packages so it can pick up the entrypoints 😕.

Highly recommend to use [Vitest](https://vitest.dev/) though.

**Comment by cstoneham** [comment]
FYI just ran into the same issue here :(

**Comment by WardenJakx** [comment]
Same here plz fix

**Comment by jxom** [comment]
PRs welcome.

**Comment by cstoneham** [comment]
@L8D FYI if you're in a pinch like me I published a version `rainmaker-prool` which exports everything from the main export as a workaround until we get this fully figured out:

```
import { anvil, createServer, CreateServerReturnType } from "rainmaker-prool";
```

it also includes a polyfill for `Promise.withResolve` which you'd likely have trouble with too.
https://github.com/ungap/with-resolvers

**Comment by jxom** [comment]
What version of Node are you running? Prool only supports Node >=22.

**Comment by jxom** [comment]
OP issue fixed via https://github.com/wevm/prool/commit/a879039aeec7e0018f51b8b7fcc11c314eba94db.

**Comment by cstoneham** [comment]
thanks @jxom!

QQ, how do we use this in our projects? I updated to `0.0.15` but still getting `Cannot find module 'prool/instances' or its corresponding type declarations.` when i try to import like this:

```
import { anvil } from "prool/instances";
```

anything I need to change?
